steps:
  - mode: "Position"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
      frame: "base_link"
      position:
        x: 50.0
        y: 0.0
        z: 20.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.0
      heading: 1.57
  - mode: "NlmpcPosition"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
      frame: "odom"
      position:
        x: 2.0
        y: 2.0
        z: 25.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.0
      heading: 0.0
