steps:
  - mode: "Position"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
      frame: "base_link"
      position:
        x: 100.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.0
      heading: 0.0
  - mode: "Position"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
      frame: "odom"
      position:
        x: 2.0
        y: 2.0
        z: 5.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.0
      heading: 0.0
