modes:
  - name: "ArmSpin"
    mode: "Spin"
    executor: "ExecutorArm"
  - name: "LandSpin"
    mode: "Spin"
    executor: "ExecutorLand"
  - name: "Position"
    mode: "Position"
    executor: "ExecutorTakeOff"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
  - name: "NlmpcPosition"
    mode: "NlmpcPosition"
    executor: "ExecutorTakeOff"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
  - name: "NlmpcWaypoints"
    mode: "NlmpcWaypoints"
    executor: "ExecutorTakeOff"
    input:
      topic: "command/waypoints"
      type: "WaypointList"
