modes:
  - name: "Spin"
    executor: "ExecutorArm"
  - name: "Position"
    executor: "ExecutorTakeOff"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
  - name: "NlmpcPosition"
    executor: "ExecutorTakeOff"
    input:
      topic: "command/pose_heading"
      type: "PoseHeading"
